# Generated by Django 3.2.3 on 2021-06-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210602_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateField(),
        ),
    ]
